### ISSUE TITLE
test-rules plugin fails when no test files changed

### ISSUE THREAD

**Issue by ties** [fortman/pre-commit-prometheus#6]
I configured `test-rules` by:
```yaml
  - id: test-rules
    entry: --entrypoint /bin/promtool prom/prometheus:latest
    always_run: true
    files: >
      (?x)^(
        files/.*\.rules_test
      )$

```

But it seems that this does not pass files to `promtool` when no test files have changed (i.e. the changes are in the rules, not tests).

```
Check prometheus rule files..........................(no files to check)Skipped
Unit test prometheus rule files..........................................Failed
- hook id: test-rules
- exit code: 1

promtool: error: required argument 'test-rule-file' not provided, try --help
```

This may be a pre-commit limitation and/or a bug in how `always_run` behaves.

## Expected behaviour

Tests are run.
